[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { varsion = "0.1", path = "../domain" }
config = "0.12.0"
serde = "1.0.136"
